version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      goreleaser-action:
        applies-to: "version-updates"
        patterns:
          - "goreleaser/goreleaser-action"
        update-types:
          - "minor"
