version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/tdtidy/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
